### ISSUE TITLE
selenium/chromedriver/linux64/122.0.6261.94/chromedriver unexpectedly exited. Status code was: 127

### ISSUE THREAD

**Issue by LucasHisabf** [simonfarah/tiktok-bot#102]
what i do?

**Comment by simonfarah** [comment]
Please provide the full error

**Comment by LucasHisabf** [comment]
> Forneça o erro completo

now i have other error in the line 8 
```
from time import sleep
from datetime import datetime
from os import system, name as os_name
from base64 import b64encode
from io import BytesIO
from requests import get, post, Session 

```

its says
 ```
File "/home/dureasd/test-siteheadless/v2.py", line 8, in <module>
  from requests import get, post, Session
ModuleNotFoundError: No module named 'requests'
```

but i have it instaled 
attrs                  23.2.0
blinker                1.4
certifi                2024.2.2
charset-normalizer     3.3.2
chromium               0.0.0
colorama               0.4.6
command-not-found      0.3
cryptography           3.4.8
dbus-python            1.2.18
distro                 1.7.0
distro-info            1.1+ubuntu0.2
exceptiongroup         1.2.0
h11                    0.14.0
httplib2               0.20.2
idna                   3.6
importlib-metadata     4.6.4
jeepney                0.7.1
keyring                23.5.0
launchpadlib           1.10.16
lazr.restfulclient     0.14.4
lazr.uri               1.0.6
more-itertools         8.10.0
netifaces              0.11.0
oauthlib               3.2.0
outcome                1.3.0.post0
packaging              23.2
pillow                 10.2.0
pip                    22.0.2
PyGObject              3.42.1
PyJWT                  2.3.0
pyparsing              2.4.7
PySocks                1.7.1
python-apt             2.4.0+ubuntu3
python-dotenv          1.0.1
PyYAML                 5.4.1
requests               2.31.0
SecretStorage          3.3.1
selenium               4.18.1
setuptools             59.6.0
six                    1.16.0
sniffio                1.3.1
sortedcontainers       2.4.0
systemd-python         234
tls-client             1.0.1
trio                   0.24.0
trio-websocket         0.11.1
typing_extensions      4.10.0
ubuntu-advantage-tools 8001
ufw                    0.36.1
unattended-upgrades    0.1
urllib3                2.2.1
wadllib                1.3.6
webdriver-manager      4.0.1
wheel                  0.37.1
wsproto                1.2.0
zipp                   1.0.0

**Comment by LucasHisabf** [comment]
i think i instaled the wrong one im going to try again

**Comment by LucasHisabf** [comment]
> Please provide the full error


████████╗██╗██╗░░██╗████████╗░█████╗░██╗░░██╗  ██████╗░░█████╗░████████╗
╚══██╔══╝██║██║░██╔╝╚══██╔══╝██╔══██╗██║░██╔╝  ██╔══██╗██╔══██╗╚══██╔══╝
░░░██║░░░██║█████═╝░░░░██║░░░██║░░██║█████═╝░  ██████╦╝██║░░██║░░░██║░░░
░░░██║░░░██║██╔═██╗░░░░██║░░░██║░░██║██╔═██╗░  ██╔══██╗██║░░██║░░░██║░░░
░░░██║░░░██║██║░╚██╗░░░██║░░░╚█████╔╝██║░╚██╗  ██████╦╝╚█████╔╝░░░██║░░░
░░░╚═╝░░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░░╚════╝░╚═╝░░╚═╝  ╚═════╝░░╚════╝░░░░╚═╝░░░

Made by : Simon Farah
Github  : https://github.com/simonfarah/tiktok-bot

------------------------------------------------------------------------

[~] Loading driver, please wait...
[!] Error loading driver: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5646ebe5be93 <unknown>
#1 0x5646ebb53ce6 <unknown>
#2 0x5646ebb886fa <unknown>
#3 0x5646ebb846ed <unknown>
#4 0x5646ebbcd71c <unknown>
#5 0x5646ebbc0c53 <unknown>
#6 0x5646ebb91db3 <unknown>
#7 0x5646ebb9277e <unknown>
#8 0x5646ebe217cb <unknown>
#9 0x5646ebe257e5 <unknown>
#10 0x5646ebe0f0e1 <unknown>
#11 0x5646ebe26372 <unknown>
#12 0x5646ebdf31bf <unknown>
#13 0x5646ebe4a488 <unknown>
#14 0x5646ebe4a683 <unknown>
#15 0x5646ebe5b044 <unknown>
#16 0x7f94103c3ac3 <unknown>

**Comment by simonfarah** [comment]
I'll check that

**Comment by LucasHisabf** [comment]
> vou verificar isso

okey i tried with sudo but got the same error too

**Comment by LucasHisabf** [comment]
> Forneça o erro completo
i made some changes and no im
```

from os import system
from time import sleep
from colorama import init, Fore
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
from selenium.common.exceptions import NoSuchElementException

init(autoreset=True)

class Bot:
    def __init__(self):
        system("cls || clear")
        self.printBanner()
        print(Fore.YELLOW + "[~] Loading driver, please wait...")

        try:
            options = Options()
            options.add_argument(
                "--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
            )
            options.add_argument('--remote-debugging-pipe')  # Adiciona o argumento aqui
            self.driver = webdriver.Chrome(options=options)

            print(Fore.GREEN + "[+] Driver loaded successfully")
            print()
        except Exception as e:
            print(Fore.RED + f"[!] Error loading driver: {e}")
            exit()

        self.url = "https://zefoy.com"
        self.captcha_xpath = "/html/body/div[5]/div[2]/form/div/div/div/div/button"
        self.services = {
            "followers": {
                "title": "Followers",
                "xpath": "/html/body/div[6]/div/div[2]/div/div/div[2]/div/button",
                "status": None,
            },
            "hearts": {
                "title": "Hearts",
                "xpath": "/html/body/div[6]/div/div[2]/div/div/div[3]/div/button",
                "status": None,
            },
            "comment_hearts": {
                "title": "Comment Hearts",
                "xpath": "/html/body/div[6]/div/div[2]/div/div/div[4]/div/button",
                "status": None,
            },
            "views": {
                "title": "Views",
                "xpath": "/html/body/div[6]/div/div[2]/div/div/div[5]/div/button",
                "status": None,
            },
            "shares": {
                "title": "Shares",
                "xpath": "/html/body/div[6]/div/div[2]/div/div/div[6]/div/button",
                "status": None,
            },
            "favorites": {
                "title": "Favorites",
                "xpath": "/html/body/div[6]/div/div[2]/div/div/div[7]/div/button",
                "status": None,
            },
        }

    def start(self):
        self.driver.get(self.url)

        print(Fore.MAGENTA + "[!] In case of a 502 Bad Gateway error")
        print(Fore.MAGENTA + "[!] please refresh the page")
        print()

        self.wait_for_xpath(self.captcha_xpath)

        print(Fore.YELLOW + "[~] Please complete the captcha")

        self.wait_for_xpath(self.services["followers"]["xpath"])

        print(Fore.GREEN + "[+] Captcha completed successfully")
        print()

        self.driver.minimize_window()
        self.check_services()

        for index, service in enumerate(self.services):
            title = self.services[service]["title"]
            status = self.services[service]["status"]

            print(Fore.BLUE + f"[{str(index + 1)}] {title}".ljust(20), status)

        while True:
            try:
                choice = int(input(Fore.YELLOW + "[-] Choose an option : "))
            except ValueError:
                continue  # This ensures the loop continues after a ValueError

            if choice in range(1, 7):
                break

        self.select_service(choice)

    def select_service(self, choice):
        div = 6 + choice
        service_key = list(self.services.keys())[choice - 1]

        self.driver.find_element(By.XPATH, self.services[service_key]["xpath"]).click()

        print()
        video_url = input(Fore.MAGENTA + "[-] Video URL : ")
        print()

        self.start_service(div, video_url)

    def start_service(self, div, video_url):
        url_input_xpath = f"/html/body/div[{div}]/div/form/div/input"
        search_btn_xpath = f"/html/body/div[{div}]/div/form/div/div/button"
        send_btn_xpath = f"/html/body/div[{div}]/div/div/div[1]/div/form/button"

        input_element = self.driver.find_element(By.XPATH, url_input_xpath)
        input_element.clear()
        input_element.send_keys(video_url)

        while True:
            # Click the search button
            self.driver.find_element(By.XPATH, search_btn_xpath).click()

            # Attempt to click the send button if it's present
            try:
                WebDriverWait(self.driver, 5).until(
                    EC.element_to_be_clickable((By.XPATH, send_btn_xpath))
                ).click()
            except TimeoutException:
                # If the send button isn't found, click the search button again
                self.driver.find_element(By.XPATH, search_btn_xpath).click()

            remaining_time = self.check_remaining_time(div)

            if remaining_time is not None:
                print(Fore.YELLOW + f"[~] Sleeping for {remaining_time} seconds")
                sleep(remaining_time)

    def check_remaining_time(self, div):
        remaining_time_xpath = f"/html/body/div[{div}]/div/div/span[1]"

        try:
            element = self.driver.find_element(By.XPATH, remaining_time_xpath)
            text = element.text

            if "Please wait" in text:
                minutes = text.split("Please wait ")[1].split(" ")[0]
                seconds = text.split(" second")[0].split()[-1]
                sleep_duration = int(minutes) * 60 + int(seconds) + 5

                return sleep_duration
            else:
                return None
        except NoSuchElementException:
            return None

    def check_services(self):
        for service in self.services:
            xpath = self.services[service]["xpath"]

            try:
                element = self.driver.find_element(By.XPATH, xpath)

                if element.is_enabled():
                    self.services[service]["status"] = Fore.GREEN + "[WORKING]"
                else:
                    self.services[service]["status"] = Fore.RED + "[OFFLINE]"
            except NoSuchElementException:
                self.services[service]["status"] = Fore.RED + "[OFFLINE]"

    def wait_for_xpath(self, xpath):
        while True:
            try:
                self.driver.find_element(By.XPATH, xpath)
                return True
            except NoSuchElementException:
                sleep(1)

    def printBanner(self):
        print(
            """
new error
```
████████╗██╗██╗░░██╗████████╗░█████╗░██╗░░██╗  ██████╗░░█████╗░████████╗
╚══██╔══╝██║██║░██╔╝╚══██╔══╝██╔══██╗██║░██╔╝  ██╔══██╗██╔══██╗╚══██╔══╝
░░░██║░░░██║█████═╝░░░░██║░░░██║░░██║█████═╝░  ██████╦╝██║░░██║░░░██║░░░
░░░██║░░░██║██╔═██╗░░░░██║░░░██║░░██║██╔═██╗░  ██╔══██╗██║░░██║░░░██║░░░
░░░██║░░░██║██║░╚██╗░░░██║░░░╚█████╔╝██║░╚██╗  ██████╦╝╚█████╔╝░░░██║░░░
░░░╚═╝░░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░░╚════╝░╚═╝░░╚═╝  ╚═════╝░░╚════╝░░░░╚═╝░░░

Made by : Simon Farah
Github  : https://github.com/simonfarah/tiktok-bot

------------------------------------------------------------------------
"""
        )


if __name__ == "__main__":
    bot = Bot()
    bot.start()

```
```

**Comment by LucasHisabf** [comment]
> Forneça o erro completo

man tu é brasileiro kkkkkkkkkk add discord ae namoral
