### ISSUE TITLE
zefoy.com not updated in a while

### ISSUE THREAD

**Issue by Ponk445** [simonfarah/tiktok-bot#107]
the site says it will soon be updated, the others were already updated last week.
follows, likes and shares are not working/were still not updated. while follows are most important next to views, likes too.
do you know when it willl appproximately be updated?

**Comment by simonfarah** [comment]
Clearly stated in the README that this is just an automation. I don't own anything or control anything on Zefoy.

**Comment by Ponk445** [comment]
Yes, I know, but it's just updating the same things, and I need followers 😭
I will use another bot.
