### ISSUE TITLE
SyntaxError: Non-ASCII character '\xc2' on line 165

### ISSUE THREAD

**Issue by hungrybearpls** [simonfarah/TikTok-Bot#11]
Hi!

I am receiving an error when trying to run the script. 

File "tiktok-bot.py", line 164
SyntaxError: Non-ASCII character '\xc2' in file tiktok-bot.py on line 165, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Any help is appreciated!

**Comment by simonfarah** [comment]
Hello! Here's an easy fix for your problem : open the script in a text editor, and on line 164, delete the copyright icon and save the file. Now run the script, it should work. Try it and let me know!
