### ISSUE TITLE
new error

### ISSUE THREAD

**Issue by rexo6565** [simonfarah/tiktok-bot#115]
Traceback (most recent call last):                                           
  File "/home/rexxxo/tiktok-bot/bot.py", line 132, in start_service
    WebDriverWait(self.driver, 5).until(
  File "/home/rexxxo/tiktok-bot/venv/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x555ee1678863 <unknown>
#1 0x555ee136e8c6 <unknown>
#2 0x555ee13b9618 <unknown>
#3 0x555ee13b96d1 <unknown>
#4 0x555ee13fc744 <unknown>
#5 0x555ee13db5cd <unknown>
#6 0x555ee13f9c19 <unknown>
#7 0x555ee13db343 <unknown>
#8 0x555ee13ac593 <unknown>
#9 0x555ee13acf5e <unknown>
#10 0x555ee163c84b <unknown>
#11 0x555ee16407a5 <unknown>
#12 0x555ee162a571 <unknown>
#13 0x555ee1641332 <unknown>
#14 0x555ee160f87f <unknown>
#15 0x555ee1667728 <unknown>
#16 0x555ee16678fb <unknown>
#17 0x555ee16779b4 <unknown>
#18 0x7f3e549123ec <unknow

**Comment by simonfarah** [comment]
Checking it

**Comment by simonfarah** [comment]
Couldn't replicate the error. Can I get a screen recording?

**Comment by simonfarah** [comment]
A new version has been pushed and should fix all raised bugs. Please try it and feel free to reopen an issue for any other bugs.
