### ISSUE TITLE
cant find file

### ISSUE THREAD

**Issue by qurwoa** [simonfarah/tiktok-bot#116]
When I download the "bot.py" file and I try to run it in a command prompt/terminal it shows "No such file or directory"
![Capture](https://github.com/simonfarah/tiktok-bot/assets/166853517/6777ac83-1455-45fc-8ea5-197d97a444c6)

**Comment by simonfarah** [comment]
That's an error in running the file nothing to do with the bot. Instructions on how to run are stated in the README.
