### ISSUE TITLE
cloudflare stuck

### ISSUE THREAD

**Issue by rebelooo** [simonfarah/tiktok-bot#119]
1) Was working fine but sudden cloudflare issue, unable to bypass at all. Currently can't be used. Zefoy is working fine on normal non bot browser.
2) Prior to this, the site threw server busy errors. Suggest bot to auto retry after X mins if so.

**Comment by Philo9899899809899098687665** [comment]
did you fix it?

**Comment by simonfarah** [comment]
Please track this issue here #114
