### ISSUE TITLE
Getting this error on shares, follows, views and like everything

### ISSUE THREAD

**Issue by axxturelmeatrider** [simonfarah/tiktok-bot#125]
![image](https://github.com/simonfarah/tiktok-bot/assets/128862683/7fe98a0f-9f58-46fe-b8ea-261b7d1c247d)

**Comment by simonfarah** [comment]
Are you by any chance choosing a service that was marked offline?

**Comment by simonfarah** [comment]
A new version has been pushed and should fix all raised bugs. Please try it and feel free to reopen an issue for any other bugs.
