### ISSUE TITLE
firefox driver can't be found!

### ISSUE THREAD

**Issue by Arashiiiii** [simonfarah/tiktok-bot#127]
![Capture d’écran 2024-09-09 002042](https://github.com/user-attachments/assets/1ae6c4c3-4eb0-4e43-93d6-a2c8e6afdcb0)
 
I did install the driver but the bot does not work

**Comment by simonfarah** [comment]
Please show me how you configured the code to access the web driver and send me the path to your web driver installation.

**Comment by Arashiiiii** [comment]
from selenium import webdriver  
from selenium.webdriver.firefox.service import Service  
from webdriver_manager.firefox import GeckoDriverManager  
import time  

service = Service(GeckoDriverManager().install())  
driver = webdriver.Firefox(service=service)  
driver.get("https://www.google.com")    

time.sleep(5) 
driver.quit()

**Comment by Arashiiiii** [comment]
my path to the webdriver is "C:\Users\HP\Desktop\geckodriver.exe" 
the latest version of selenium doesn't require the path in code I guess

**Comment by simonfarah** [comment]
Remove those lines, I tested it with your setup and it works
https://github.com/simonfarah/tiktok-bot/blob/c588d6f906a6fb7f2d7b987a4ff015ed5298a5cf/bot.py#L44
https://github.com/simonfarah/tiktok-bot/blob/c588d6f906a6fb7f2d7b987a4ff015ed5298a5cf/bot.py#L49

**Comment by Arashiiiii** [comment]
works fine now. thanks!
