### ISSUE TITLE
I have a error 

### ISSUE THREAD

**Issue by Dilovan200** [simonfarah/TikTok-Bot#13]
I habe this problem 
Can u help ???

Traceback (most recent call last):                                                                          File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,                                                      File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 966, in __init__                  self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 1840, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)                                          FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.termux/files/home/TikTok-Bot/chromedriver.exe'                                                                                              
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/TikTok-Bot/tiktok-bot.py", line 182, in <module>
    driver = webdriver.Chrome(PATH)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by simonfarah** [comment]
Hello, looks like the it's a chromedriver path error, which means that you put the chromedriver in the wrong directory. It should be placed in the same directory as the script. Just like this :

![img](https://user-images.githubusercontent.com/88495690/143907849-d452abfa-f8e4-4a5e-afa2-635ae4b7d07a.png)

However, the issue could also be due to you not using windows and not adjusting the script as I mentioned in the README file.

**Comment by Dilovan200** [comment]
like this ?
![2022-02-04 (1)](https://user-images.githubusercontent.com/92992933/152525070-72853f7c-d445-4574-9411-a38fb00b8fec.png)

**Comment by simonfarah** [comment]
Exactly! Now you can run the script, and it should work. Let me know.

**Comment by Dilovan200** [comment]
okey have that now but somehow come now that. What am I doing wrong?
![2022-02-04 (2)](https://user-images.githubusercontent.com/92992933/152554770-08555e5b-63b2-47b0-875a-ed39f462fde3.png)

**Comment by Dilovan200** [comment]
I want to make him and me followers only 1k each so we can go live we were together in switzerland in prison now he sits in Spanish alkatraz XP and I don't know so well with programming or writing scripts myself am still newbie

**Comment by simonfarah** [comment]
Okay the script is running fine! It's just that the followers option is not available on zefoy right now. Under the followers tab in the browser you can see in red "soon will be update", which means that this option is unavailable right now. However, it looks like the other options are available, you can run the script to generate them! You can run the script maybe after a few hours or a day to see if the followers option is available again.

**Comment by Dilovan200** [comment]
okey Thanks
