### ISSUE TITLE
error loading driver

### ISSUE THREAD

**Issue by LIL-KAV** [simonfarah/tiktok-bot#131]
[~] Loading driver, please wait...
[x] Error loading driver: Message: Unable to locate or obtain driver for firefox; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

**Comment by simonfarah** [comment]
This is a web driver installation issue, it may vary depending on your browser, installed driver, configuration. Nothing related to the code itself. You may refer to some instructions in the README or the selenium docs.
