### ISSUE TITLE
Chrome driver

### ISSUE THREAD

**Issue by Baaltra** [simonfarah/TikTok-Bot#16]
Hi,

I try to download chrome driver but i can’t, I have chrome version 98 and i’m on windows x64. Can you help me pls ?

(sorry for the english i’m french)

Thanks

**Comment by simonfarah** [comment]
Hello! I don't actually know what issue you are facing, however, you can download the chrome driver for chrome version 98 from [here](https://chromedriver.storage.googleapis.com/index.html?path=98.0.4758.80/). Choose the one for windows. Let me know if you are stuck anywhere, I'll be pleased to help!
