### ISSUE TITLE
Could you tell me what I am doing wrong?

### ISSUE THREAD

**Issue by xanderusa** [simonfarah/TikTok-Bot#17]
I followed all your steps but when clicking on the tikto-bot.py it doesn't happen anything. https://streamable.com/6imrc5 chromedriver is same version as my chrome browser which is 98. I installed colorama and the other component. and nothing has worked. Please help.

**Comment by simonfarah** [comment]
Hello. Can you please run the script via your terminal to see which errors
you are getting?

**Comment by xanderusa** [comment]
Hi. I just run a test in CMD and this is the error what I've got (error 2) or something https://streamable.com/xtf369

**Comment by xanderusa** [comment]
Hello. I've run a test in my terminal and I've got (errorno 2) or something. https://streamable.com/uge5ew

**Comment by simonfarah** [comment]
Your second command is wrong. It should be `python tiktok-bot.py` or simply `tiktok-bot.py`

**Comment by xanderusa** [comment]
Got it. It worked, but when I am going to open the titkok-bot from the folder directly as per your instructions it still doesn't open. It seems it only works if I execute it from the terminal: https://streamable.com/1xrpdc

**Comment by simonfarah** [comment]
You are very welcome! Glad to hear that it worked at least from the terminal. Well actually if you go to zefoy and paste the URL it will work of course and it will generate 1000 views, but you will have to repeat the same process every 5 minutes to get new 1000 views. So here comes the role of the bot, it will do the exact same process all day long as long as you are running the script, and you'll have to complete the captcha only once. Now answering why the script isn't running when clicking on the 'tiktok-bot.py' file, I'll say that it's an installation problem on your machine and the script doesn't have to do with this. And a lucky guess is that you did not add Python to PATH when installing Python. You can search on google on how to add Python to PATH, hoping that this is the problem. Let me know if this will work, else, I can't really help if I'm not seeing any errors. Hope that this helped! Waiting to hear from you to see if it works.

**Comment by xanderusa** [comment]
Ok. I reinstalled Python this time making sure it went to a PATH, and also, I kept open the chromedriver open as you said, then also, I disabled antivirus, ad blockers etc just to see if that was the problem, but still the samee. https://streamable.com/pd9a7a

**Comment by simonfarah** [comment]
Ok let's go step by step here. 

First, when I say keep your chromdriver open, I do not mean to open the chromedriver.exe, just do not touch this file. What I mean is when you run the script, a Google Chrome tab will open, this is the chromedriver!

Second, to fix the problem you are facing, it looks like your python files run by default in the Python Interactive Shell. So to get them run by default in the cmd as we want, do this.
- Right click on the tiktok-bot.py file
- Click on Open With > Choose another app
- From the list choose Python or search for it
- Check the box where it says: Always use this app to open .py file

Now your python files should run by default in the cmd.

**Comment by xanderusa** [comment]
ok. I did and still same. I screenshot it because it only remains half second and it says: "Traceback (most recent call last):". So I decided to make a cmd terminal test and now this is what I've got: 

![image](https://user-images.githubusercontent.com/99228482/154995789-b20c4ae7-cf50-453a-b386-6f08a94f4177.png)

**Comment by simonfarah** [comment]
You did not install selenium as I mentioned in the installation documentation!!
Run this command `pip install selenium==3.141.0` then run the script

**Comment by xanderusa** [comment]
Oh my lord. God bless you man. It worked 🙏 you are a genious. I really admire you ppl. This thing programming world is fascinating. Thank you very much!

**Comment by simonfarah** [comment]
You are very welcome!! Glad that I could help. You can always get in touch with me - on Instagram 'simonfarah_' or via email simonfarah@pm.me - when you need extra help. See ya!
