### ISSUE TITLE
A generic error occurred. Now will retry again

### ISSUE THREAD

**Issue by darkhacknet** [simonfarah/TikTok-Bot#18]
The error "A generic error occurred. Now will retry again" is displayed just after set the video URL on the option 2 "Get followers" the error is displayed all the time in that specific option.

**Comment by simonfarah** [comment]
Hello! It's just probably that the followers option is not available on zefoy right now. Under the followers button in the browser you would see in red "soon will be update", which means that this option is unavailable right now. You can run the script maybe after a few hours or a day to see if the followers option is available again.

**Comment by simonfarah** [comment]
You're welcome, I will keep this issue open until I get a confirmation from you.
