### ISSUE TITLE
You didn't solve the captcha yet. Need to refresh to avoid endless loop.

### ISSUE THREAD

**Issue by xuvt** [simonfarah/TikTok-Bot#19]
when i start the bot i get that error after a few seconds even tho i manually solved it.

**Comment by simonfarah** [comment]
Hello! A wild guess is that the option you chose is not available on zefoy right now. For exemple, under the followers button in the browser you would see in red "soon will be update", which means that this option is unavailable right now. Can you please check if this is the case? If not, I'll look into it.

**Comment by cruzj2000** [comment]
i am having the same problem too and ive tried using an option thats on available
