### ISSUE TITLE
once insertting a link and choosing an option it closes:

### ISSUE THREAD

**Issue by Przlyy** [simonfarah/TikTok-Bot#22]
Once i insert my link for the video and choose my option it just instantly closes python, my chrome drive and chrome version are the sanme (both 99). I have everything in the same folder aswell, im not srue what to do.

**Comment by Przlyy** [comment]
also when i try to open chrome driver manually my pc blocks it, maybe thats the problem?

**Comment by simonfarah** [comment]
Hello! Can you please run the script in your terminal to see what errors you are getting.

**Comment by Przlyy** [comment]
oh my i feel dumb for asking this, but how do i actually do that?

**Comment by simonfarah** [comment]
You open your terminal/cmd, drag and drop the tiktok-bot.py file in the terminal/cmd then click "enter"

**Comment by Przlyy** [comment]
> You open your terminal/cmd, drag and drop the tiktok-bot.py file in the terminal/cmd then click "enter"

I just opens the code in python

**Comment by simonfarah** [comment]
I understand, but I want you to run the code via your terminal to see why it's not working for you.

**Comment by Maca777** [comment]
<img width="1418" alt="Screen Shot 2022-03-07 at 2 19 40 PM" src="https://user-images.githubusercontent.com/101078822/157111624-821b198c-c897-4ff0-a75c-34d11e1ad75e.png">

I am just now starting out with python and thought it would be cool to try something like this that is pre-built and all I have to do is look at the code myself to get a better understanding of how the code works. However whenever I try and run it this always comes up, I'm on MacBook and don't know what to do because I am not running windows. Im new to this wouldn't be surprised if I did something wrong LOL

**Comment by simonfarah** [comment]
> <img width="1418" alt="Screen Shot 2022-03-07 at 2 19 40 PM" src="https://user-images.githubusercontent.com/101078822/157111624-821b198c-c897-4ff0-a75c-34d11e1ad75e.png">

Hello! Looks like you didn't put the chromedriver in the correct path. Install the correct chromedriver, unzip the downloaded zip file, copy and paste the executable chromedriver in the tiktok-bot.py directory.

**Comment by Maca777** [comment]
> > <img alt="Screen Shot 2022-03-07 at 2 19 40 PM" width="1418" src="https://user-images.githubusercontent.com/101078822/157111624-821b198c-c897-4ff0-a75c-34d11e1ad75e.png">
> 
> Hello! Looks like you didn't put the chromedriver in the correct path. Install the correct chromedriver, unzip the downloaded zip file, copy and paste the executable chromedriver in the tiktok-bot.py directory.

Is there anyway you could help me to show me how to do this? Im not sure how to do it, do you have any videos that I could look up, or if you have any you could share so I could have a better understanding of what to do? I don't know how to put the chrome driver in the correct path as well as those other steps you told me to do.

**Comment by simonfarah** [comment]
I have a video, but it's not published on youtube or elsewhere and I won't probably publish it. I'm only sending it privately to those who need it. Do you have telegram so I can send it to you?

**Comment by Maca777** [comment]
Yeah I have a telegram, @ElChapoGottaGlocko is my username on telegram. I appreciate all the help :)

**Comment by Meht610** [comment]
> J’ai une vidéo, mais elle n’est pas publiée sur youtube ou ailleurs et je ne la publierai probablement pas. Je ne l’envoie qu’en privé à ceux qui en ont besoin. Avez-vous un télégramme pour que je puisse vous l’envoyer?

Hello i have the same problem, can you send me the video? https://t.me/ethan610
