### ISSUE TITLE
tengo algunos problemas

### ISSUE THREAD

**Issue by matedor159** [simonfarah/TikTok-Bot#23]
al momento de poner el link y darle a followers me sale las siguientes lineas:

D:\tiktok\TikTok-Bot-main\TikTok-Bot-main\tiktok-bot.py:182: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(PATH)
Traceback (most recent call last):
  File "D:\phyton\lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "D:\phyton\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\phyton\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\tiktok\TikTok-Bot-main\TikTok-Bot-main\tiktok-bot.py", line 182, in <module>
    driver = webdriver.Chrome(PATH)
  File "D:\phyton\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "D:\phyton\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 90, in __init__
    self.service.start()
  File "D:\phyton\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

y tengo el chromedriver en la carpeta de tiktok-bot-main

**Comment by matedor159** [comment]
![a](https://user-images.githubusercontent.com/63132120/157175820-366319fb-e062-4fff-9dd6-7ef3b4fbffc6.PNG)

**Comment by matedor159** [comment]
![image](https://user-images.githubusercontent.com/63132120/157175892-35e585ee-11a3-4dea-982a-facddb88d4ae.png)

**Comment by simonfarah** [comment]
which version of selenium are you using?

**Comment by matedor159** [comment]
> que version de selenium estas usando?
instale la ultima version usando en el cmd el:   pip install selenium

**Comment by simonfarah** [comment]
try pip install selenium==3.141.0

**Comment by matedor159** [comment]
ahora me sale esto:
![image](https://user-images.githubusercontent.com/63132120/157316970-77b76c26-73dd-4e85-ac3f-28268bbb22c0.png)

**Comment by simonfarah** [comment]
So here are a few solutions to try, but first make sure that your chromedriver is the same version of your chrome browser.

So some solutions here:

1 - Insert the path to chromedriver manually. So open the script using a text editor, and edit the PATH variable to
`C:/Users/your_path/chromedriver.exe`

2- Put 'chromedriver.exe' in
`C:\Python27\Scripts` or wherever you installed Python and then you need not to provide the path of driver, just open the script file in a text editor, delete the L
PATH variable, then edit the line under to
`driver= webdriver.Chrome()`

**Comment by matedor159** [comment]
ahora abre y cierra automaticamente una ventana de chrome y me bota el siguiente mensaje, instale el chrome driver con pip install chromedrive==99.0.4844.51:
![image](https://user-images.githubusercontent.com/63132120/157320246-5a80ed36-7d6c-4b4e-b40b-096f792bc674.png)

**Comment by simonfarah** [comment]
your chrome driver and chrome browser are NOT the same version. You have chrome version 99 but chromedriver version 100. Either upgrade chrome to version 100 or install the chromedriver version 99. And there's nothing called pip install chromedrive==xxxxx
