### ISSUE TITLE
 Not a full bug but when i start the bot after getting thru the picking of likes or shares it stops with an error including PATH

### ISSUE THREAD

**Issue by SomeSmallBrain** [simonfarah/TikTok-Bot#25]
- Device: [Samsung A40]
 - OS: [Android]
 - Browser [e.g. chrome]
 - Version [99.4 and I'm too lazy to type it entire]

**Additional context**
Nothing 
![Screenshot_20220318-170142_Termux](https://user-images.githubusercontent.com/101885981/159038797-c3b9b348-2dff-45e2-a0d1-381349987b05.jpg)

**Comment by xtekky** [comment]
You need to replace the  chromedriver path in the script, DM me on https://t.me/xtekky, or discord xtekky#9031

**Comment by simonfarah** [comment]
you can't run this script on android unless you can follow up with [this article ](https://jitblog.net/selenium-chromedriver-for-android/)

**Comment by simonfarah** [comment]
> @SomeSmallBrain You need to replace the chromedriver path in the script, DM me on https://t.me/xtekky, or discord xtekky#9031, I will help you, also maybe this zefoy script will help you out: [github.com/zefoy](https://github.com/xtekky/zefoy)

Wrong information. Please do not respond to issues unless you know the correct answer.
