### ISSUE TITLE
Build it into request tiktok bot

### ISSUE THREAD

**Issue by Discord-Monkey** [simonfarah/TikTok-Bot#28]
We dont want to use auto matc zefoy proccess bc it needs us verify and etc...
make it easier = import requests , time 
and do views and captcha solving thanks

**Comment by simonfarah** [comment]
I don't think we can make it happen using requests. I'll look into it anyway. If you have any ideas on how to do it, please let me know here.

**Comment by Discord-Monkey** [comment]
Hmm u can use pyfidget and requests 
getting response ffrom api and get it threading "header" so ............. I have made one but patched
hope it help!
can u contact me in discord?
Discord:  Di$cord#8548

**Comment by simonfarah** [comment]
yes, I'll get in touch on discord soon.

**Comment by Discord-Monkey** [comment]
okay
