### ISSUE TITLE
the program is ok，but 502

### ISSUE THREAD

**Issue by wangyuxu** [simonfarah/TikTok-Bot#29]
i am use M1 bookpro ,i run all code by readme,but m1 pop a window 502 badway ,please tell me how to resolve the question?
![11081649411247_ pic](https://user-images.githubusercontent.com/20733331/162411355-46f3d7f6-e05b-45db-bbaa-ab6306a43384.jpg)

**Comment by simonfarah** [comment]
Hello, plz check this issue #20 and if you need more assistance you can always contact me.

**Comment by wugongxing** [comment]
same error 502
