### ISSUE TITLE
when i open the py file it closes (pls be quick lol)

### ISSUE THREAD

**Issue by itzCozi** [simonfarah/TikTok-Bot#32]
**To Reproduce**
1. Go to 'tiktok-bot'
2. Click on '2'
3. it closes

**Expected behavior**
chrome driver opens i do capcha
 
**Screenshots**
![Screenshot 2022-04-18 221716](https://user-images.githubusercontent.com/93058744/163906859-3a700ce7-dafa-4da4-ab0a-60fe10a3254d.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [desktop on win 10 (winver:21h2]
 - Browser [chrome/brave/opra]
 - Version [21h2]

**Additional context**
pls be quick help a script kiddy out

**Comment by simonfarah** [comment]
Can I please get to know what errors you are getting

**Comment by itzCozi** [comment]
there are no errors if its easy add my dis Cozi#4200 
we can hop in call and ill screen share no one has to use mic
