### ISSUE TITLE
run the python script get the link pres number 4 and it starts itself then it just closes the program

### ISSUE THREAD

**Issue by neko5star** [simonfarah/TikTok-Bot#36]
hi i am havinf problems with program when i enter url and number and pres enter the porgram just closes itself  and that is it i only found chrome driver 100 32bit version can you guy help me if you can it would be great
![Screenshot (4)](https://user-images.githubusercontent.com/80632782/164914332-cff1be85-4e41-483d-afbe-4480629aeb1e.png)
![Screenshot (3)](https://user-images.githubusercontent.com/80632782/164914334-bd28a7eb-d70f-47c7-8876-d40ccef5c1e1.png)

**Comment by simonfarah** [comment]
can you please run the script in your terminal and send me the error you get

**Comment by neko5star** [comment]
> can you please run the script in your terminal and send me the error you get   
what do you mean by that? could you write down steps of what to do

**Comment by simonfarah** [comment]
open your terminal, drag and drop the python script file into the terminal and hit the enter key

**Comment by simonfarah** [comment]
Sorry can't teach you basic stuff here. Check on Google how to run a python script in your terminal
