### ISSUE TITLE
i am confused on what to do after i install selenium and colorama.

### ISSUE THREAD

**Issue by col1insmellsbad** [simonfarah/TikTok-Bot#38]

**Comment by col1insmellsbad** [comment]
here what i get after trying to use
![Screenshot 2022-04-24 013714](https://user-images.githubusercontent.com/69518961/164958234-d21a7217-b03b-4620-a652-f789ceeca3a8.png)
 tiktok-bot.py

**Comment by simonfarah** [comment]
Sorry I can't teach you the basic commands of the command prompt. Check on Google how to run a script or how to use your cmd
