### ISSUE TITLE
Shares doesnt work.

### ISSUE THREAD

**Issue by Bronac** [simonfarah/TikTok-Bot#4]
Tried views. It works fine. But when I try shares it clicks share inserts the link and presses search but it doesnt actually press the share black button. Please see the attached image. It only goes upto pressing search and then exits back to the home page. In the console the error reads Á generic error has occured
![df](https://user-images.githubusercontent.com/55746446/140855570-8ac43792-f7ab-410c-96e5-2e65b06402cf.PNG)
".

**Comment by simonfarah** [comment]
Issue is fixed! Please try it and let us know.
P.S : looks like zefoy is sometimes updating its source code which will cause a malfunction in the code. Your opened issues in this repository will let me know when an issue appears so I can fix it, so thank you for your contribution!
