### ISSUE TITLE
when i type "pip" it just doesnt recongnize it

### ISSUE THREAD

**Issue by comradeduck** [simonfarah/TikTok-Bot#40]
yes the title says it, when i try to download colorama, i follow what the tutorial says. so i go to cmd type in pip install colorama. didnt do anything and sorry if im annoying but im super new i just downloaded python so could you help me please?

**Comment by daveyedgartanibulie** [comment]
> yes the title says it, when i try to download colorama, i follow what the tutorial says. so i go to cmd type in pip install colorama. didnt do anything and sorry if im annoying but im super new i just downloaded python so could you help me please?

I can but when I write down the number it immediately comes out

**Comment by UnixCro** [comment]
Note: The author is a lying ruthless dog.  But he can do one thing.  don't build bad things...

**Comment by simonfarah** [comment]
No response. Issue will be closed.
