### ISSUE TITLE
Tiktok bot not working

### ISSUE THREAD

**Issue by LemonJam1** [simonfarah/TikTok-Bot#43]
Even after having solved the captcha and refreshed zefoy.com, I still get the "You didn't solve the captcha yet. Need to refresh to avoid endless loop" when trying to generate views on a video. The pop up browser just refreshes every 20 seconds.
I also get 502 bad gateway every now and then, any way I can get around this?

**Comment by simonfarah** [comment]
Hello. If the browser shows a 502 bad gateway, try refreshing the page manually (even try refreshing multiple times). If the 502 message still occurs, try to get a good vpn and rerun the bot.

**Comment by hacknapier** [comment]
TikTok Captcha Solving Service is available here with demo to Login successfully into your TikTok Account.
https://rapidapi.com/flyCaptcha/api/flycaptcha
