### ISSUE TITLE
chromedriver error

### ISSUE THREAD

**Issue by 77PC** [simonfarah/TikTok-Bot#44]
**Describe the bug**

**To Reproduce**
1. pip install -r requirements then download chrome driver version 102 linux unzip it move it to the bot directory
2. chmod +x chromedriver
3. remove the .exe in the tiktok-bot.py 
4. run the script and see the error

**Expected behavior**
i expected it to send the comment likes to the video that i precised

**Screenshots**
screen of the error
![20220627_220911](https://user-images.githubusercontent.com/105139814/176027335-f82aaf31-8983-4ab6-9604-25c4e2420b7f.jpg)

**Desktop (please complete the following information):**
 - OS: [Android 10]
 - Browser [chrome 102.0.5005.125]

**Smartphone (please complete the following information):**
 - Device: [samsung j6]
 - OS: [ANDROID 10]
 - Browser [chrome]
 - Version [102.0.5005.125]
 - Termux [0.118.0]

**Comment by maulaaskaputri** [comment]
Send me script tiktok followers

Pada tanggal Sel, 28 Jun 2022 3.13 AM, 77PC ***@***.***>
menulis:

**Comment by simonfarah** [comment]
Hello! You can't run this script directly on your android phone since there is a lot more steps to do in order to run the chromedriver on a smartphone.

**Comment by 77PC** [comment]
so you can't help me ??
