### ISSUE TITLE
Cant open?

### ISSUE THREAD

**Issue by ChoppedOn** [simonfarah/TikTok-Bot#5]
I am new to all of this so maybe this is my fault but i cant seem to open the tiktok-bot.py file.
I have python, selenium and the correct chrome driver installed but whenever I try to open the file it opens then closes automatically.

**Comment by simonfarah** [comment]
Hello! So the problem might be a module that you didn't install yet, most probably the colorama module. Here's what to do, open cmd/terminal and type the following command : pip install colorama
And be sure that your chromedriver is in the same directory/folder of the tiktok-bot.py file.
Now try to run the script, it should work. If not, please open the file using cmd/terminal and tell us what errors you are getting.

**Comment by ChoppedOn** [comment]
Yes thank you it was the colorama module. Working now :)

**Comment by simonfarah** [comment]
Great to hear that!
