### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by ItsMeDitzzy** [simonfarah/TikTok-Bot#6]
![Screenshot_2021-11-20-09-54-52-467_com microsoft rdc androidx](https://user-images.githubusercontent.com/53190401/142712194-9357f6a2-0cba-42f6-83e8-6c779772e312.jpg)

How to fix it?, already using vpn proxy still can't work

**Comment by simonfarah** [comment]
hello, this error in this case is due to one of the following options:
1- an error from zefoy servers, which is usually fixed within minutes
2- you are using a vpn or a proxy, so try to not use any of them
