### ISSUE TITLE
no internet connection

### ISSUE THREAD

**Issue by genharris1** [simonfarah/tiktok-bot#68]
the driver doesn't load, and I have no internet, even if I am connected. I am not behind proxies or firewalls!

**Comment by quintendewilde** [comment]
I have the same issue

**Comment by quintendewilde** [comment]
Nevermind I get the same issue!

**Comment by quintendewilde** [comment]
I'm running the bot and receiving this instantly.

[~] Loading driver, please wait...
[!] No internet connection

I have the chromedriver in the same folder, but it doesn't start up from my experience. 
I've launched manually, but it doesn't recognize it.

I have no other error code.

**Comment by simonfarah** [comment]
you don't have to manually put the chromedriver. do you have chrome installed? did you install all the dependency list?

**Comment by simonfarah** [comment]
vpn is turned off, no proxies, internet is working?

**Comment by simonfarah** [comment]
must be the uc wasn't installed correctly. glad that it works

**Comment by simonfarah** [comment]
The problem was that `undetected_chromedriver` was not working with the latest chrome version. Issue is now fixed, please run `pip install -r requirements.txt` again and the bot will work.
