### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Mist420** [simonfarah/TikTok-Bot#7]
So when I open the the bot it works opening it but when i try to add followers or anything the app just colses and I get nothing downloaded all the things downloaded chromedriver_win32 and exracted it from a zip to a normal file and put it in TikTok-Bot-main'
Can you help me or send me a tutorial video?

**Comment by Mist420** [comment]
![image](https://user-images.githubusercontent.com/95108929/143662208-1e0c11a7-b461-4b62-a121-aa6b84e3bdd0.png)
This pops up sorry for bad quailty but it closes in a instants so had no time to even screen shot it or copy it had to record and had to go frame to frame to find it

**Comment by simonfarah** [comment]
Hello! Thank you for reporting your problem.
To fix it, you need to open your Command Prompt and type the following command : pip install selenium==3.141.0

I'll explain what the issue is. I actually wrote the script using selenium 3, however, there's now selenium 4, which is what you probably installed of course. After reading the new version change-log, there are quite many lines of code to change, but I'd prefer staying on version 3 and keeping the script as it is. 
I'll probably share the script used with selenium 4 in a new branch when I finish reading the complete change-log.

**Comment by Mist420** [comment]
https://youtu.be/vDvylfGhkuE Here is a video of me doing all of it step by step still not working

**Comment by simonfarah** [comment]
Ohh I see what you did wrong. You are putting the chromedriver inside of a folder that you created. Just put it outside that folder next to the tiktok-bot.py file. If this still doesn't work, I'll make a youtube video and send you the link.

**Comment by Mist420** [comment]
Still not working https://youtu.be/19bwq73SgWU

**Comment by simonfarah** [comment]
Alright. One more try before making a youtube video. Rename your "chromedriver.exe" to "chromedriver"

**Comment by Mist420** [comment]
Still can't when I do it doesnt work

**Comment by KuroSenseii** [comment]
its can't working because zefoy.com its DOWN

**Comment by Mist420** [comment]
Its not down i just used it LOL

mån 29 nov. 2021 kl. 04:30 skrev Kuro ***@***.***>:

**Comment by KuroSenseii** [comment]
yeah sur .... 502 Bad Gateway i dont know how you can use a website down LOL

**Comment by Mist420** [comment]
Disable VPN if you're using one they have anti vpn and gives you 502 bad gateway if you're using a vpn

**Comment by KuroSenseii** [comment]
i dont use vpn so i imagine their anti-vpn is doing shit lol

**Comment by Mist420** [comment]
Yea maybe

**Comment by Mist420** [comment]
![image](https://user-images.githubusercontent.com/95108929/143867952-3f52d65e-fa6f-4d54-9ed8-51a0065e3f5f.png)

**Comment by simonfarah** [comment]
![img](https://user-images.githubusercontent.com/88495690/143907849-d452abfa-f8e4-4a5e-afa2-635ae4b7d07a.png)
All what you need to do is to download the code from this repository and set everything up, download the correct version of the chromedriver, and put them in a folder like this. I really don't know what's going wrong on your pc, this never happened to anybody before. Please retry again while I'm still trying to figure out the problem.

**Comment by Mist420** [comment]
Ok 1 of all what chrome version Should i use and what python version should
I used and look at the message above I sent a screen shot of the error msg

mån 29 nov. 2021 kl. 17:46 skrev Simon Farah ***@***.***>:

**Comment by Mist420** [comment]
Just please make a video tutorial for windows 10

**Comment by VanceTrieschmann** [comment]
I would also appreciate a video tutorial that shows step-by-step on how to set it all up! I would even be willing to pay lmao.
