### ISSUE TITLE
Bot not working for some reason

### ISSUE THREAD

**Issue by HNuWin21** [simonfarah/tiktok-bot#72]
Whenever I try to click on the bot file nothing is loaded. I also try to type in pip install requirement but it keep saying ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
https://github.com/simonfarah/tiktok-bot/assets/64929622/f8a56885-840b-4d24-8346-064a953bda3e

**Comment by simonfarah** [comment]
You must open the terminal and run this command in the bot directory. Please note that the bot has been updated so please be sure that you have the latest version.
