### ISSUE TITLE
cloudflare "verify you are human" loop

### ISSUE THREAD

**Issue by KiwaRii** [simonfarah/tiktok-bot#74]
Stuck on this verifying human thing, i've tried several times from restart the bot or refresh page but sill stuck on this thing
any resolve for it?
![image](https://github.com/simonfarah/tiktok-bot/assets/128950224/280f6ffa-2574-44f0-99cd-c21d9e131132)

**Comment by HydraCoderX** [comment]
same here

**Comment by web-spidy** [comment]
same here

**Comment by jarwonozt** [comment]
It seems like this problem occurs in all TikTok bot tools, I'm also surprised.

**Comment by simonfarah** [comment]
solved here https://github.com/simonfarah/tiktok-bot/issues/76#issuecomment-1718676106.
