### ISSUE TITLE
looping human verification 

### ISSUE THREAD

**Issue by Racheltjhia** [simonfarah/tiktok-bot#75]
please fix cloudflare human bot verification

**Comment by vioan** [comment]
The same issue for me, as well

**Comment by BruhNeedsScripts** [comment]
i have the issue as well

**Comment by scaynn** [comment]
same issue

**Comment by jkk5442** [comment]
open zefoy.com in a new tab in the same window. verification will complete. go back to the tab opened by script , solve captcha there and good to go. worked for me.

**Comment by simonfarah** [comment]
solved here https://github.com/simonfarah/tiktok-bot/issues/76#issuecomment-1718676106.
thank you @jkk5442
