### ISSUE TITLE
No internet connection(solved) - New Issue - Looping Verification

### ISSUE THREAD

**Issue by jkk5442** [simonfarah/tiktok-bot#76]
while loading the driving, chrome opens with a flash. and then it says No internet Connection.

**Comment by jkk5442** [comment]
I updated my chrome to latest version and this issue is solved. But now looping Human Verification!!

**Comment by UhhOneLargeCoke** [comment]
I opened a tab next to it with zefoy.com than solved the captcha then went back and I was in.

**Comment by jkk5442** [comment]
yesss it worked.. thanks for sharing

**Comment by simonfarah** [comment]
> I opened a tab next to it with zefoy.com than solved the captcha then went back and I was in.

Thank you! Working on a fix for it
