### ISSUE TITLE
seems to get an error when running 

### ISSUE THREAD

**Issue by thisisnotthedroidyouarelooking4** [simonfarah/tiktok-bot#80]
Exception ignored in: <function Chrome.__del__ at 0x0000015FE756A2A0>
Traceback (most recent call last):
\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 843, in __del__
    self.quit()
AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 798, in quit
    time.sleep(0.1)
OSError: [WinError 6] The handle is invalid

although chrome is installed

**Comment by simonfarah** [comment]
More context please. When does this occur?

**Comment by HNuWin21** [comment]
same thing happens to me. It happens with I run the bot. Here's an image of what my page looks like
![Screenshot 2023-09-19 203014](https://github.com/simonfarah/tiktok-bot/assets/64929622/33de6514-75cd-495a-8f16-642f1a9baef8)

**Comment by simonfarah** [comment]
Do you have chrome installed along with all the requirements?
