### ISSUE TITLE
无法 打开

### ISSUE THREAD

**Issue by Minko5858** [simonfarah/tiktok-bot#87]
I was able to get in at first, but the chrome driver didn't validate the code until I updated undetected_chromedriver and selenium, and then when I opened it, it kept saying that the network wasn't connecting, so I'm asking if your problem is due to updating these two or if there's another problem.
![Screenshot 2023-10-02 213749](https://github.com/simonfarah/tiktok-bot/assets/124525174/cad7d328-e965-4c49-a0cb-57ae9e90bb6b)

**Comment by mosespace** [comment]
i have the same issue at #88 🥹🥹

**Comment by Julienbase** [comment]
same issue

**Comment by luckyirmina19** [comment]
This issue because of Chrome version. Need to update the latest version. I had the same issue and update Chrome to 119.0.6045.66 and it’s working fine ✅.

**Comment by mohammealhal** [comment]
> I was able to get in at first, but the chrome driver didn't validate the code until I updated undetected_chromedriver and selenium, and then when I opened it, it kept saying that the network wasn't connecting, so I'm asking if your problem is due to updating these two or if there's another problem. ![Screenshot 2023-10-02 213749](https://private-user-images.githubusercontent.com/124525174/272010350-cad7d328-e965-4c49-a0cb-57ae9e90bb6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MjI3OTQsIm5iZiI6MTcwNTUyMjQ5NCwicGF0aCI6Ii8xMjQ1MjUxNzQvMjcyMDEwMzUwLWNhZDdkMzI4LWU5NjUtNGM0OS1hMGNiLTU3YWU5ZTkwYmI2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QyMDE0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmYwOWJjZWIzYjZhZjBkNDkwYzU1ODRlNThjY2NmNWRmOTlkNzFhN2FkNGE3MWU5YWZhOTFlNTkwMjgyNjQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4UhoMF_OCWBC8pPhgfssWP8mCRYtcAWoVnHcTeUaJFo)

**Comment by xuia1** [comment]
SAME  IISSSUUEEE

**Comment by simonfarah** [comment]
Hello. A new update was just pushed. Please check it and let me know if everything's working good.
