### ISSUE TITLE
Bug: [!] No internet connection

### ISSUE THREAD

**Issue by mosespace** [simonfarah/tiktok-bot#88]
### Am Getting the following error and of which am connected to super fast and stable network

What could be the cause?

![image](https://github.com/simonfarah/tiktok-bot/assets/111237257/93ba1c82-71da-4fde-a379-da8600511b09)

**Comment by bonzayy** [comment]
.

**Comment by luckyirmina19** [comment]
This issue because of Chrome version. Need to update the latest version. I had the same issue and update Chrome to 119.0.6045.66 and it’s working fine ✅.

**Comment by bannawee** [comment]
try : pip install -r requirements.txt

**Comment by hello12332145** [comment]
how do i update it
