### ISSUE TITLE
i cant run it , help

### ISSUE THREAD

**Issue by Spdyback** [simonfarah/tiktok-bot#89]
![image](https://github.com/simonfarah/tiktok-bot/assets/118689075/29efab36-f5f8-4d2f-951e-660d624ac222)
what do i do

**Comment by BlancoV8** [comment]
im stuck on the same thing

**Comment by BlancoV8** [comment]
> ![image](https://private-user-images.githubusercontent.com/118689075/273326787-29efab36-f5f8-4d2f-951e-660d624ac222.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMTI0ODIsIm5iZiI6MTcwMTMxMjE4MiwicGF0aCI6Ii8xMTg2ODkwNzUvMjczMzI2Nzg3LTI5ZWZhYjM2LWY1ZjgtNGQyZi05NTFlLTY2MGQ2MjRhYzIyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEzMFQwMjQzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYWI1Y2U1ODdjMTQ2MjkyNWQ4OGIwNmJjMTFjNGU5ZGE3ZmFkZTAxN2NkOTQ5YWM3M2U1NTAyYTljN2YzZGVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WCvb4DiXBu2TWH_dbVv5zKUutJu3EBMKcLzUoE4PynU) what do i do

try unistalling python 12 and downloading python 11.6.4 this solved my problem
