### ISSUE TITLE
i get this error

### ISSUE THREAD

**Issue by Botmakingisafunsport** [simonfarah/TikTok-Bot#9]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/anonym/TikTok-Bot/chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tiktok-bot.py", line 182, in <module>
    driver = webdriver.Chrome(PATH)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by simonfarah** [comment]
Try running this command : pip install selenium==3.141.0
Then try to run the script again. If this still doesn't work, you might be using the wrong version of the chrome driver. The chrome driver version must be the same as your google chrome browser.
And if none of the above is working, please tell so I can try to solve the error you're getting.

**Comment by simonfarah** [comment]
no response, issue will be closed

**Comment by hungrybearpls** [comment]
Receiving similar error. 

Have ChromeDriver installed in /usr/local/

Do I have to change this path to the bot folder?

HB

**Comment by simonfarah** [comment]
Hello! Thank you for sharing the issue. So the script is running fine on my local machine, so lets try to find a solution for you. On line 181, replace `PATH = os.getcwd() + "/chromedriver.exe"` with `PATH = "./chromedriver.exe"`, save the file and rerun the script. If this still doesn't work, send me a screenshot of your installation directory, and I'll be working on another solution.

**Comment by hungrybearpls** [comment]
Got it to work, however the likes to the hearts on the video did not increase.

**Comment by simonfarah** [comment]
Great to hear. Well for the likes, that would be a zefoy problem, I can't control that.
