### ISSUE TITLE
ModuleNotFoundError: No module named 'Undetected_Chromedriver'

### ISSUE THREAD

**Issue by BenjaminnRWT** [simonfarah/tiktok-bot#91]
![image](https://github.com/simonfarah/tiktok-bot/assets/47344411/3bb971ed-0671-48b9-af87-bfc5e8117d34)

How do you solve this? Please help

**Comment by BlancoV8** [comment]
if you cd into where you have the requirements.txt folder saved into this should resolve the problem

**Comment by simonfarah** [comment]
Hello. A new update was just pushed with more precise instructions. Please check it and let me know if everything's working good.
