### ISSUE TITLE
dont know what to do

### ISSUE THREAD

**Issue by theguy12345234** [simonfarah/tiktok-bot#92]
please help

**Comment by theguy12345234** [comment]
how do i install the required modules into the code directory?

**Comment by theguy12345234** [comment]
what the hell is a code directory. HOW AM I SUPPOSED TO DOWNLOAD SOMET IF YOU DONT GIVE GOOD DIRECTIONS

**Comment by jrmessiah** [comment]
> what the hell is a code directory. HOW AM I SUPPOSED TO DOWNLOAD SOMET IF YOU DONT GIVE GOOD DIRECTIONS

If you dont even know what is a code directory then you shouldnt even be doing all these GENIUS. It means go into the folder of the bot and install requirements....jesus christ.

**Comment by allelive** [comment]
> che diavolo è una directory di codici. COME POSSO SCARICARE QUALCOSA SE NON DAI BUONE ISTRUZIONI

segui queste istruzioni nel terminale copia e incollali nel terminale uno alla vota

cd tiktok-bot
pip install -r requirements.txt 
python3.8 bot.py 
attendi che ti si apre la finestra web e inserisci il ciacra scrivi le lettere che vedi nello scermo e poi ritorni al terminale puoi utilizzare solo visualizzazione e condivisione come opsioni per i follower e offline

**Comment by BlancoV8** [comment]
> what the hell is a code directory. HOW AM I SUPPOSED TO DOWNLOAD SOMET IF YOU DONT GIVE GOOD DIRECTIONS

although i have zero clue on python or command prompt, the instructions are quite clear. if you open command prompt and you do the command    cd tiktok-bot-main , it should open the folder that your tiktok bot is saved into. after that you are able to the pip install -r requirements.txt after that fully opens the do the command   python bot.py it should then open up the captcha then answer that and boom your all set, for my bot to work i had to download python 11.6.4, python 12 did not have disituils downloaded.

**Comment by simonfarah** [comment]
Hello. A new update was just pushed along with precise instructions. Please check it and let me know if everything's working good.
