### ISSUE TITLE
Heart and Follow not available

### ISSUE THREAD

**Issue by ngtrgiabao** [simonfarah/tiktok-bot#93]
![image](https://github.com/simonfarah/tiktok-bot/assets/95952006/b46d4e0f-d58c-4a2c-96b5-b2ff87cc1d40)

**Comment by anuptamang9550** [comment]
https://vt.tiktok.com/ZSNynA6kp/

**Comment by anuptamang9550** [comment]
https://vt.tiktok.com/ZSNynA6kp/

**Comment by ngtrgiabao** [comment]
> https://vt.tiktok.com/ZSNynA6kp/

video is not available

**Comment by simonfarah** [comment]
This is related to zefoy and not the code. Nothing could be done.
