### ISSUE TITLE
502 error even after refreshing

### ISSUE THREAD

**Issue by Clyde-Timonera** [simonfarah/tiktok-bot#94]
![image](https://github.com/simonfarah/tiktok-bot/assets/78290310/8bd9e4ae-913a-418e-96b1-270d97fd9b44)

**Comment by UNSCORP** [comment]
same with me

**Comment by Sf786336** [comment]
I encounter this problem when using both Mac and Windows

**Comment by simonfarah** [comment]
Hello. A new update was just pushed. Please check it and let me know if everything's working good.
