### ISSUE TITLE
not responding after inserting a link

### ISSUE THREAD

**Issue by liad142** [simonfarah/tiktok-bot#95]
Hi  ,

The bot isnt working . none of the options if working .

after inserting a link there is no response 

![image](https://github.com/simonfarah/tiktok-bot/assets/74761087/14abe56f-a6e2-400e-996b-ec53f2eba1e5)

**Comment by AnonymouslyAnonymous89** [comment]
I'm getting the same red offline for followers as well.

**Comment by AnonymouslyAnonymous89** [comment]
From what I understand, the follower option is offline for maintenance.

**Comment by liad142** [comment]
I tried the Views options not the Followers option . but none of the options are working for me

**Comment by AnonymouslyAnonymous89** [comment]
When you run the bot - does chrome automatically open up asking you to fill out the captcha ? And then after you verify that , does this pop up   ...   

![Web capture_25-12-2023_142554_zefoy com](https://github.com/simonfarah/tiktok-bot/assets/45220294/46a0df68-ba36-4672-a0a8-1c1253eaf69d)

**Comment by Okeke-Divine** [comment]
DITTO387FGN4

**Comment by AnonymouslyAnonymous89** [comment]
@Okeke-Divine  What??

**Comment by liad142** [comment]
> When you run the bot - does chrome automatically open up asking you to fill out the captcha ? And then after you verify that , does this pop up ... The reason i'm asking is because I see your using pasting the video URL into terminal, not the chrome UI.
> 
> Might not be the issue, but could be.
> 
> ![Web capture_25-12-2023_142554_zefoy com](https://private-user-images.githubusercontent.com/45220294/292776340-46a0df68-ba36-4672-a0a8-1c1253eaf69d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1Nzc0NzksIm5iZiI6MTcwMzU3NzE3OSwicGF0aCI6Ii80NTIyMDI5NC8yOTI3NzYzNDAtNDZhMGRmNjgtYmEzNi00NjcyLWEwYTgtMWMxMjUzZWFmNjlkLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQwNzUyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzliMmIwNWI0YWRiZmRmNGFjZjRiM2Y1YjY3YWFjMjIwMDQ4ZjFiZjRhN2NkOGNlNjAyZDBhN2JmNzllYjQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Z__4PND48SaiL0JhejTqgsbtHJhp52fVV-lZtKCpD_E)

Chrome doesnt show up after running the bot  ..

**Comment by Azert12A** [comment]
Can someone explain to me how to install the bot on my PC?

**Comment by simonfarah** [comment]
Hello. A new update was just pushed. Please check it and let me know if everything's working good.
