### ISSUE TITLE
Option #1 - Follower = offline.

### ISSUE THREAD

**Issue by AnonymouslyAnonymous89** [simonfarah/tiktok-bot#96]
I was able to get it all up and running, besides the follower option #1. It says offline, while the rest say online. Is there something that usually causes this, or is does something need to get updated on this end?

**Comment by mohammealhal** [comment]
> I was able to get it all up and running, besides the follower option #1. It says offline, while the rest say online. Is there something that usually causes this, or is does something need to get updated on this end?
