### ISSUE TITLE
I got an error

### ISSUE THREAD

**Issue by z4dev** [simonfarah/tiktok-bot#98]
/usr/local/bin/python3 /Users/rashed/Desktop/rootFolder/tiktok_bot/tiktok
-bot/bot.py
Traceback (most recent call last):
  File "/Users/rashed/Desktop/rootFolder/tiktok_bot/tiktok-bot/bot.py", line 4, in <module>
    import undetected_chrome_driver as uc
ModuleNotFoundError: No module named 'undetected_chrome_driver'

**Comment by Valhallxkx** [comment]
That module is not installed you can try "pip install undetected_chrome_driver" or "pip install -r requirements.txt

**Comment by simonfarah** [comment]
Hello. A new update was just pushed. Please check it and let me know if everything's working good.
