### ISSUE TITLE
When entering the function, it gives an error and the bot closes

### ISSUE THREAD

**Issue by padla438** [simonfarah/tiktok-bot#99]
Tell me what I'm doing wrong, I seem to have installed all the libraries, Google has the latest version.

**Comment by padla438** [comment]
![Uploading image 2024-02-12-000900.png…]()

**Comment by padla438** [comment]
<img width="662" alt="image 2024-02-12-000900" src="https://github.com/simonfarah/tiktok-bot/assets/156339320/e694a632-20eb-4d87-a1b3-2931e71f4c9d">

**Comment by padla438** [comment]
<img width="662" alt="image 2024-02-12-000900" src="https://github.com/simonfarah/tiktok-bot/assets/156339320/32443a3f-9de7-457b-b2b0-c1fc9abbc2ec">

**Comment by padla438** [comment]
<img width="662" alt="image 2024-02-12-000900" src="https://github.com/simonfarah/tiktok-bot/assets/156339320/b5a0a999-3cc9-496b-8c99-c8ca19aad3a2">

**Comment by padla438** [comment]
![Uploading image 2024-02-12-000900.png…]()

**Comment by padla438** [comment]
<img width="662" alt="image 2024-02-12-000900" src="https://github.com/simonfarah/tiktok-bot/assets/156339320/2dc9bddf-6f83-4295-9f33-4369641264bb">

**Comment by simonfarah** [comment]
Hello. A new update was just pushed. Please check it and let me know if everything's working good.
